version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels:
      - go
      - dependencies
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: "daily"
    labels:
      - docker
      - dependencies
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    labels:
      - github-actions
      - dependencies
