name: "bank"
services:
    postgres:
        image: postgres:15.6-alpine
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: bank_service
        ports:
            - "5432:5432"
    xbankapi:
        build: .
        restart: always
        environment:
            DATABASE_URL: postgres://admin:admin@postgres:5432/bank_service?sslmode=disable
        ports:
            - "3000:3000"
