// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package storage

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID    uuid.UUID
	Email        string
	Name         string
	CurrencyCode string
}

type Transaction struct {
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        pgtype.Numeric
	SourceID      uuid.NullUUID
}
