// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockDBConnection is an autogenerated mock type for the DBConnection type
type MockDBConnection struct {
	mock.Mock
}

type MockDBConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBConnection) EXPECT() *MockDBConnection_Expecter {
	return &MockDBConnection_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockDBConnection) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBConnection_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockDBConnection_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDBConnection_Expecter) Begin(ctx interface{}) *MockDBConnection_Begin_Call {
	return &MockDBConnection_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockDBConnection_Begin_Call) Run(run func(ctx context.Context)) *MockDBConnection_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDBConnection_Begin_Call) Return(_a0 pgx.Tx, _a1 error) *MockDBConnection_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBConnection_Begin_Call) RunAndReturn(run func(context.Context) (pgx.Tx, error)) *MockDBConnection_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockDBConnection) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBConnection_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDBConnection_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDBConnection_Expecter) Ping(ctx interface{}) *MockDBConnection_Ping_Call {
	return &MockDBConnection_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockDBConnection_Ping_Call) Run(run func(ctx context.Context)) *MockDBConnection_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDBConnection_Ping_Call) Return(_a0 error) *MockDBConnection_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBConnection_Ping_Call) RunAndReturn(run func(context.Context) error) *MockDBConnection_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBConnection creates a new instance of MockDBConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBConnection {
	mock := &MockDBConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
